services:
  mask-detection-api:
    build: .
    image: face-mask-image
    ports:
      - "8000:8000"
    environment:
      - USE_AWS=true
      - AWS_REGION=eu-north-1
      - S3_BUCKET=face-mask-audit-trail-om-44
      - DYNAMO_TABLE=mask-detections
      - CW_NAMESPACE=FaceMaskDetection

  streamlit:
    image: face-mask-image
    command: streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://mask-detection-api:8000/predict